# Options
set -g default-terminal "tmux-256color"
set -sg terminal-overrides ",*:RGB"  # true color support
set -g escape-time 0  # disable delays on escape sequences
set -g mouse on
set -g renumber-windows on  # keep numbering sequential
set -g repeat-time 1000  # increase "prefix-free" window

#List of plugins
#set -g @plugin 'tmux-plugins/tmux-sensible'
#set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'tmux-plugins/tmux-fzf'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'tmux-plugins/tmux-prefix-highlight'
#set -g @plugin 'jimeh/tmuxifier'
set -g @plugin 'tmux-plugins/tmux-autoreload'
set -g @continuum-restore 'on'
#set -g @plugin 'erikw/tmux-powerline'
#set -g @tmux_power_theme 'everforest'
#set -g @plugin 'catppuccin/tmux#v2.1.3'
set -g @plugin 'tmux-plugins/tmux-cpu'
set -g @continuum-save-interval '15'
set -g @continuum-restore 'on'
set -g @resurrect-capture-pane-contents 'on'
set -g @resurrect-strategy-nvim 'session'
set -g @resurrect-processes 'yazi gemini node htop nvim lazygit'
# set -g @resurrect-dir '~/.config/tmux/resurrect'
set -g @plugin 'tmux-plugins/tpm'

# Options: start indexes from 1
set -g base-index 1
set -g pane-base-index 1

# Change prefix
unbind C-b
set -g prefix C-Space
bind C-Space send-prefix

# Theme: borders
#set -g pane-border-lines simple
set -g pane-border-style fg=black,bright
set -g pane-active-border-style fg=magenta

# Theme: status
set -g status-style bg=default,fg=black,bright
#set -g status-position "top"
set -g status-left ""
set -g status-left-length 0
#set -g status-right ""
#set -g status-right "#[fg=white,bg=#3B4252] #{pane_current_command} #[default]"
set -g status-right '#{cpu_fg_color} 󰻠 #{cpu_percentage} #{ram_fg_color} 󰍛 #{ram_percentage}#{?#{==:#{gpu_percentage},No GPU},, #{gpu_fg_color}  #{gpu_percentage}}#[default] '


# Configure the catppuccin plugin
#set -g @catppuccin_flavor "mocha"
#set -g @catppuccin_window_status_style "rounded"

# Theme: status (windows)
set -g window-status-format " #I.#W "
set -g window-status-current-format " #I.#W "
set -g window-status-separator "  "

set -g window-status-style "fg=white,bg=#3B4252,reverse"
set -g window-status-current-style "fg=white,bg=blue,bold"
set -g window-status-bell-style "fg=white,bg=yellow"

# Keybindings: wasd
bind k select-pane -U
bind h select-pane -L
bind j select-pane -D
bind l select-pane -R

bind -r K resize-pane -U
bind -r H resize-pane -L
bind -r J resize-pane -D
bind -r L resize-pane -R

# Keybindings: disable repeat for arrows
bind Up select-pane -U
bind Left select-pane -L
bind Down select-pane -D
bind Right select-pane -R

# Keybindings: split
bind ` split-window -h
bind \\ split-window -h
bind v split-window -v
bind - split-window -v
# 关闭当前 pane 不再需要确认 (覆盖默认的 x 绑定)
bind-key x kill-pane
# 关闭当前 window 不再需要确认 (覆盖默认的 & 绑定)
bind-key & kill-window

# Keybindings: windows
bind -n C-Tab next-window
bind -n C-S-Tab previous-window

bind -n M-1 select-window -t :1
bind -n M-2 select-window -t :2
bind -n M-3 select-window -t :3
bind -n M-4 select-window -t :4
bind -n M-5 select-window -t :5
bind -n M-6 select-window -t :6
bind -n M-7 select-window -t :7
bind -n M-8 select-window -t :8
bind -n M-9 select-window -t :9

# Keybindings: other
bind f resize-pane -Z
bind q detach-client
bind e choose-window -Z

bind -n M-w select-pane -U
bind -n M-a select-pane -L
bind -n M-s select-pane -D
bind -n M-d select-pane -R
bind -n M-f resize-pane -Z

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.config/tmux/plugins/tpm/tpm'
